### ISSUE TITLE
Upgrade to 4.1 fails

### ISSUE THREAD

**Issue by webmozart** [ApiGen/ApiGen#590]
The upgrade to ApiGen 4.1 fails for me with the following error:

> Config "/vendor/apigen/theme-default/src/config.neon' was not found

Reproduce:

1. Clone https://github.com/puli/api.puli.io
2. Change "apigen/apigen" version in composer.json to "4.1.*"
3. Run `make`

**Comment by TomasVotruba** [comment]
Should be fixed in 4.1.1. Could you try?

**Comment by webmozart** [comment]
Awesome, works :) Thanks!

**Comment by TomasVotruba** [comment]
Great!

**Comment by vaidas-lungis** [comment]
Can you release 4.1.1 version? It is only tagged. 
At the moment composer does not fetch latest release.

**Comment by jadb** [comment]
I have been unable to update composer because it is still showing under @TomasVotruba as maintainer so even triggering a manual update for composer doesn't work on my side (for now).

**Comment by TomasVotruba** [comment]
@jadb I've just moved you my position of maintainer. Could you check if everything works now?

**Comment by philjohn** [comment]
Hmmm, I'm still getting this with 4.1.1 - I'm using a different path for dependencies, "src/dependencies". Worked with older versions of apigen, but looks like it's expecting to live in /vendor/ now ...
